# -*- coding: utf-8 -*-
"""Python Project Interest Rate Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xyTTE9LF_21PTCjuwEna4yaGHllaGXzo

Extracting Data From Fred Data Base
"""

import pandas_datareader.data as web
import pandas as pd
from datetime import datetime
from pandas.tseries.offsets import MonthBegin

start = datetime(2014,1,1)
end = datetime(2025,11,30)

fred_df = pd.DataFrame()
fred_df['USD_INR'] = web.DataReader('DEXINUS', 'fred', start, end)
fred_df['CPI_USA'] = web.DataReader('MEDCPIM158SFRBCLE', 'fred', start, end)
fred_df['Crude_Oil'] = web.DataReader('DCOILWTICO', 'fred', start, end)
fred_df['Trade_Balance_India'] = web.DataReader('XTEXVA01INM667S ', 'fred', start, end)
fred_df['US_Rate_EFFR'] = web.DataReader("FEDFUNDS", "fred", start, end)

"""Interpolating missing Data with Previous Values and averaging out the data on monthly basis"""

fred_df.reset_index(inplace=True)
fred_df['USD_INR'] = fred_df['USD_INR'].interpolate(method='linear', limit_direction='both')
fred_df['Crude_Oil'] = fred_df['Crude_Oil'].interpolate(method='linear', limit_direction='both')
fred_df.resample('ME',on ='DATE').mean()
fred_df.dropna(inplace=True)

"""Converting all dates to start of the month"""

fred_df['DATE']=pd.to_datetime(fred_df['DATE'],format='%m%Y',errors='coerce')
fred_df = fred_df.dropna(subset=['DATE'])
fred_df['DATE'] = fred_df['DATE'] - MonthBegin(1)
fred_df.rename(columns={'DATE':'Date'},inplace=True)
fred_df

"""Extracting RBI Repo Rate From Website

import pandas as pd
import requests
import io
url = 'https://basunivesh.com/rbi-repo-rate-history-from-2000/'
header = {
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
}
response = requests.get(url, headers=header)
tables = pd.read_html(io.StringIO(response.text))
repo_df = tables[0]
repo_df.columns = repo_df.iloc[0]
repo_df = repo_df[1:].reset_index(drop=True)
repo_df['Date'] = repo_df['Date'].str.replace('–', '-', regex=False)
repo_df['Date'] = pd.to_datetime(repo_df['Date'], dayfirst=True)
repo_df['RBI Repo Rate'] = repo_df['RBI Repo Rate'].str.replace('%', '', regex=False).astype(float)
repo_df.to_excel('RBI_Repo_Rate.xlsx', index=False)

Was getting bloacked by website so downloaded html to extract the data for the same
"""

import pandas as pd
import io
from bs4 import BeautifulSoup
file_path = 'RBI Repo Rate History from 2000 to 2025 (5th December 2025).html'
with open(file_path, 'r', encoding='utf-8') as f:
    html_content = f.read()
tables = pd.read_html(io.StringIO(html_content))
repo_df = tables[0]
repo_df.columns = repo_df.iloc[0]
repo_df = repo_df[1:].reset_index(drop=True)
repo_df['Date'] = repo_df['Date'].str.replace('–', '-', regex=False)
repo_df['Date'] = pd.to_datetime(repo_df['Date'], dayfirst=True, errors='coerce')
repo_df = repo_df.dropna(subset=['Date'])
repo_df['Date'] = repo_df['Date'] - MonthBegin(1)
repo_df['RBI Repo Rate'] = repo_df['RBI Repo Rate'].astype(str).str.replace('%', '', regex=False).astype(float)
repo_df

"""Importing data from excel about Foreign Exchange Reserves"""

import pandas as pd
import warnings
warnings.simplefilter(action='ignore', category=UserWarning)
df = pd.read_excel('Foreign Exchange Reserves.xlsx', skiprows=3)
reserves_df = df.iloc[2:].copy()
new_column_names = list(df.columns)
new_column_names[13] = 'Total_Reserves_USD'
reserves_df.columns = new_column_names
reserves_df['Year'] = pd.to_numeric(reserves_df['Year'], errors='coerce')
reserves_df = reserves_df.dropna(subset=['Year']).reset_index(drop=True)
reserves_df['Date'] = pd.to_datetime(
    reserves_df['Year'].astype(int).astype(str) + '-' + reserves_df['Month'].astype(str) + '-01',
    format='%Y-%b-%d'
)
reserves_df = reserves_df[[ 'Date', 'Total_Reserves_USD']]
reserves_df

"""Importing Indian CPI data from Excel"""

import pandas as pd
cpi_df=pd.read_excel('rbi_cpi_IND.xlsx',skiprows=5)
cpi_df=cpi_df[1:]
clmns=list(cpi_df.columns)
clmns[1]='Date'
clmns[5]='Ind_CPI'
cpi_df.columns=clmns
cpi_df=cpi_df[['Date','Ind_CPI']]
cpi_df = cpi_df.dropna(subset=['Date','Ind_CPI'])
cpi_df['Date']=pd.to_datetime(cpi_df['Date'],errors='coerce') - MonthBegin(1)
cpi_df['Ind_CPI']=pd.to_numeric(cpi_df['Ind_CPI'],errors='coerce')
cpi_df

"""Merging all dataframes into one and cleaning the data."""

from typing_extensions import final
dfs=[fred_df,repo_df,reserves_df,cpi_df]
final_df=dfs[0]
for nxt in dfs[1:] :
  final_df = pd.merge(final_df, nxt, on='Date',how='outer')
final_df = final_df.ffill()
final_df = final_df.where(final_df['Date']>'2014-01-01')
final_df.dropna(inplace=True)
final_df.set_index('Date',inplace=True)
final_df
#final_df.to_excel('final_df.xlsx',index=False)

"""Plot for USD/INR for given period"""

import matplotlib.pyplot as plt
final_df['USD_INR'].plot(title='USD/INR')
plt.show()

y = final_df['USD_INR']
x = final_df.copy()

"""Scaled down the data for correlation"""

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaled = pd.DataFrame(
    scaler.fit_transform(x),
    columns=x.columns,
    index=x.index
)

"""Plot of correlation Matrix"""

import seaborn as sns
plt.figure(figsize=(10, 8))
sns.heatmap(x_scaled.corr(), annot=True,cmap='coolwarm')
plt.title("Macro Economic Correlation Matrix")
plt.show()

x_scaled = x_scaled.drop(columns=['USD_INR'])

"""Calculate Variance Inflation Factor for Dataset to detect Multicollinearity in regression and found out that Trade Balance and Total resrves are highly correlated and redundant"""

from statsmodels.stats.outliers_influence import variance_inflation_factor
vif = pd.DataFrame()
vif["Variable"] = x_scaled.columns
vif["VIF"] = [
    variance_inflation_factor(x_scaled.values, i)
    for i in range(x_scaled.shape[1])
]
vif

"""Finding the best fit line using Ordinary Least Squares based on dependennt variables
Found that main drivers of Exchange rate is US EFFR, US CPI, Total Reserves, surprizingly rbi rate and IND cpi are not well related to USD/INR
"""

import statsmodels.api as sm
x_ols = sm.add_constant(x_scaled)
ols_model = sm.OLS(y,x_ols).fit()
print(ols_model.summary())

"""ADF test to find if exhange rate is stationary or not.
Non stationary data gives bad eresult in OLS as The data has a trend
"""

from statsmodels.tsa.stattools import adfuller
adf_result = adfuller(y)
print(f"ADF Statistic: {adf_result[0]}")
print(f"p-value: {adf_result[1]}")

y

"""Converting exchange rates to Difference in exhange rate Month Over Month"""

y_diff = y.diff().dropna()
y_diff

"""Re-Testing for ADF on Change in exchange rate MoM"""

from statsmodels.tsa.stattools import adfuller

adf_diff = adfuller(y_diff)
print(f"ADF Statistic (diff): {adf_diff[0]}")
print(f"p-value (diff): {adf_diff[1]}")

"""ADF on rest of the data"""

data_cols = ['CPI_USA','Crude_Oil','Trade_Balance_India',
             'US_Rate_EFFR','RBI Repo Rate','Total_Reserves_USD','Ind_CPI']

for col in data_cols:
    stat, p, *_ = adfuller(final_df[col].dropna())
    print(col, round(p,4))

"""Converting data into change in MoM"""

exog = final_df[['CPI_USA','Crude_Oil','Trade_Balance_India',
                 'US_Rate_EFFR','RBI Repo Rate','Total_Reserves_USD','Ind_CPI']]

exog_diff = exog.diff().dropna()

"""Recalculating ADF on MoM Difference"""

for col in exog_diff.columns:
    stat, p, *_ = adfuller(exog_diff[col])
    print(col, round(p,4))

"""Scaling down the MoM change data using Standard Scaler"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
exog_scaled = pd.DataFrame(
    scaler.fit_transform(exog_diff),
    columns=exog_diff.columns,
    index=exog_diff.index
)

"""Reindexing data after MoM change"""

y_diff = final_df['USD_INR'].diff().dropna()
y_final = y_diff.loc[exog_diff.index]

"""SARIMAX model (past value=1, no of difference=1, error terms =0) on MoM change of data
showing total reserves is one of the most important factor for USD/INR
The variable ar.L1 has a P-value of 0.000 and The coefficient -0.5459 means that if the USD_INR rate jumped up significantly last month, there is a strong mathematical tendency for it to pull back this month.
"""

from statsmodels.tsa.statespace.sarimax import SARIMAX
model = SARIMAX(
    y_final,
    exog=exog_scaled,
    order=(1,1,0),
    enforce_stationarity=False,
    enforce_invertibility=False
)

result = model.fit()
print(result.summary())

"""Plotting  ARIMAX Residuals"""

import matplotlib.pyplot as plt
plt.figure(figsize=(10,4))
plt.plot(result.resid)
plt.title("ARIMAX Residuals")
plt.show()

"""Forcasting next 6 MoM chnage in USD/INR around forcasted mean within confidance interval"""

forecast = result.get_forecast(
    steps=6,
    exog=exog_scaled.iloc[-6:]
)
forecast_mean = forecast.predicted_mean
forecast_ci = forecast.conf_int()
print(forecast_mean)

"""Plot of ARIMAX Forecast"""

plt.figure(figsize=(10,4))
plt.plot(y_final, label='Actual')
plt.plot(forecast_mean, label='Forecast', color='red')
plt.fill_between(
    forecast_ci.index,
    forecast_ci.iloc[:,0],
    forecast_ci.iloc[:,1],
    color='red',
    alpha=0.2
)
plt.legend()
plt.title("USD/INR ARIMAX Forecast")
plt.show()

"""Converting MoM change back to USD/INR using last actual value"""

last_actual = final_df['USD_INR'].iloc[-1]
usd_inr_forecast_level = last_actual + forecast_mean.cumsum()
forecast_df = pd.concat([
    final_df['USD_INR'],
    usd_inr_forecast_level
])
forecast_df.tail(7)

"""Final Forecasted Plot Of USD/INR"""

import matplotlib.pyplot as plt

plt.figure(figsize=(10,4))

plt.plot(final_df['USD_INR'], label='Actual USD/INR', linewidth=2)
plt.plot(usd_inr_forecast_level, label='Forecast USD/INR',
         color='red', linestyle='--', linewidth=2)

plt.axvline(final_df.index[-1], color='black', linestyle=':', label='Forecast Start')

plt.title('USD/INR Actual vs ARIMAX Forecast')
plt.xlabel('Date')
plt.ylabel('USD/INR Level')
plt.legend()
plt.grid(alpha=0.3)
plt.show()

"""Training Model And Testing Again, so spliitting data into train and test data"""

split_date = '2024-01-01'

y_train = y_final.loc[:split_date]
y_test  = y_final.loc[split_date:]

exog_train = exog_scaled.loc[y_train.index]
exog_test  = exog_scaled.loc[y_test.index]

"""SARIMAX on Test Data"""

model = SARIMAX(
    y_train,
    exog=exog_train,
    order=(1,1,0),
    enforce_stationarity=False,
    enforce_invertibility=False
)

result = model.fit()

"""Final Forecast Of Test Data"""

forecast_test = result.get_forecast(
    steps=len(y_test),
    exog=exog_test
)

y_pred = forecast_test.predicted_mean

"""Mean Absolute Error & Mean Squared error on Model"""

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("MAE:", round(mae,3))
print("RMSE:", round(rmse,3))

"""Side By Side comparison of Actual VS Forecasted FX Data"""

last_train_level = final_df.loc[y_train.index[-1], 'USD_INR']
usd_inr_forecast_test_level = last_train_level + y_pred.cumsum()
usd_inr_actual_test = final_df.loc[y_test.index, 'USD_INR']
comparison_df = pd.DataFrame({
    'Actual_USD_INR': usd_inr_actual_test,
    'Forecast_USD_INR': usd_inr_forecast_test_level
})
comparison_df = comparison_df.dropna()
print(comparison_df.head())

"""Plot For the same"""

import matplotlib.pyplot as plt
plt.figure(figsize=(10,4))

plt.plot(comparison_df.index,
         comparison_df['Actual_USD_INR'],
         label='Actual USD/INR',
         linewidth=2)

plt.plot(comparison_df.index,
         comparison_df['Forecast_USD_INR'],
         label='Forecast USD/INR',
         linestyle='--',
         linewidth=2)

plt.title('USD/INR: Actual vs ARIMAX Forecast (Test Period)')
plt.xlabel('Date')
plt.ylabel('USD/INR Level')
plt.legend()
plt.grid(alpha=0.3)

plt.show()